version: "3"
services:
  nginx:
    image: commojun/oauth2-proxy-test:latest
    ports:
      - 8891:8891
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/auth/:/etc/nginx/auth/:ro
      - ./oauth2_proxy.conf:/oauth2_proxy.conf:ro
      - ./authenticated_emails:/authenticated_emails:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

