version: "3"
services:
  nginx:
    image: commojun/oauth2-proxy-test:latest
    ports:
      - 8891:8891
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d/:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

